<?php

use Symfony\Component\Yaml\Yaml;

require_once __DIR__ . '/../vendor/autoload.php';

class SpannedGenerator
{
    /** @var array<string, array | string> */
    private array $ast;

    public function __construct()
    {
        $this->ast = Yaml::parseFile(__DIR__ . '/../../crates/pxp-ast/meta/ast.yaml');
    }

    public function generate(): string
    {
        $output = <<<'RUST'
        // This file is generated by meta/scripts/generate-spanned.php.
        // Do not make modifications to this file directly.

        use pxp_span::Spanned;
        use crate::generated::*;


        RUST;

        return $output;
    }
}

$generator = new SpannedGenerator();

file_put_contents(__DIR__ . '/../../crates/pxp-ast/src/spanned.rs', $generator->generate());

echo "Generated `Spanned` implementations.\n";